server:
  port: 8080
  address: 0.0.0.0


spring:
  application:
    name: fraud-detection-service

  # ---------------- Kafka Configuration ----------------
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: fraud-detection-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  # ---------------- PostgreSQL Configuration ----------------
  datasource:
    url: jdbc:postgresql://fraud-postgres:5432/banking_fraud_detection_db
    username: fraud_user
    password: fraud_pass
    driver-class-name: org.postgresql.Driver

  # ---------------- JPA / Hibernate ----------------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ---------------- Flyway ----------------
  flyway:
    enabled: true
    locations: classpath:db/migration

# ---------------- Logging ----------------
logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    com.bankfraud: DEBUG
    org.apache.kafka: WARN
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO

# ---------------- Management Endpoints ----------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
